### ISSUE TITLE
Erreur 502 sur l'importation V_FORMATION_DIPLOME (Pleiade)

### ISSUE THREAD

**Issue by gasilber** [mission-apprentissage/referentiel#107]
Erreur ce matin 7/2/2023:

```
[ERROR][production] {
  name: 'referentiel',
  hostname: 'c35153af7b82',
  pid: 106,
  context: 'script',
  level: 50,
  err: {
    message: 'Request failed with status code 502',
    name: 'AxiosError',
    code: 'ERR_BAD_RESPONSE',
    config: {
      transitional: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: {},
      headers: [Object],
      url: 'https://infocentre.pleiade.education.fr/bcn/index.php/export/CSV?n=V_FORMATION_DIPLOME&separator=%7C',
      method: 'get',
      httpAgent: [Object],
      httpsAgent: [Object],
      responseType: 'stream'
    },
    request: '[Circular]',
    response: {
      status: 502,
      statusText: 'Proxy Error',
      headers: [Object],
      config: '[Circular]',
      request: '[Circular]',
      data: '[Circular]'
    }
  },
  msg: 'Request failed with status code 502',
  time: '2023-02-07T06:01:06.973Z',
  v: 0
}
```

qui semble déconnecter le client MongoDB et impacter la suite du processus d'importation des autres fonds:

```
[ERROR][production] {
  name: 'referentiel',
  hostname: 'c35153af7b82',
  pid: 106,
  context: 'import',
  level: 50,
  err: {
    message: 'MongoClient must be connected to perform this operation',
    name: 'MongoNotConnectedError',
    stack: 'MongoNotConnectedError: MongoClient must be connected to perform this operation\n' +
      '    at getTopology (/app/node_modules/mongodb/lib/utils.js:282:11)\n' +
      '    at /app/node_modules/mongodb/lib/operations/execute_operation.js:19:48\n' +
      '    at maybePromise (/app/node_modules/mongodb/lib/utils.js:409:5)\n' +
      '    at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:16:37)\n' +
      '    at Collection.updateOne (/app/node_modules/mongodb/lib/collection.js:169:57)\n' +
      '    at writeData.parallel (/app/src/jobs/importDatagouv.js:86:54)\n' +
      '    at ParallelWrite._onWrite (/app/node_modules/oleoduc/lib/writeData.js:99:25)\n' +
      '    at ParallelWrite._write (/app/node_modules/oleoduc/lib/writeData.js:47:8)\n' +
      '    at doWrite (node:internal/streams/writable:411:12)\n' +
      '    at clearBuffer (node:internal/streams/writable:572:7)'
  },
  msg: "Impossible d'importer l'organisme de formation  82380416638",
  time: '2023-02-07T06:01:11.975Z',
  v: 0
}
```

**Comment by gasilber** [comment]
Ne s'est plus produit récemment.
