### ISSUE TITLE
Erreur lors du build

### ISSUE THREAD

**Issue by gasilber** [mission-apprentissage/referentiel#111]
```
[2023-02-14T08:48:09.734Z][ERROR][script] aborted
Error: aborted
    at connResetException (node:internal/errors:717:14)
    at TLSSocket.socketCloseListener (node:_http_client:462:19)
    at TLSSocket.emit (node:events:525:35)
    at node:net:322:12
    at TCP.done (node:_tls_wrap:588:7) 
{ err: {} }
[2023-02-14T08:48:10.004Z][WARN][collect] Erreur lors de la collecte pour l'organisme 30540504500025. { source: 'sirene' } 
{
  anomalies: [
    MongoNotConnectedError: MongoClient must be connected to perform this operation
        at getTopology (/app/node_modules/mongodb/lib/utils.js:282:11)
        at /app/node_modules/mongodb/lib/operations/execute_operation.js:19:48
        at maybePromise (/app/node_modules/mongodb/lib/utils.js:409:5)
        at executeOperation (/app/node_modules/mongodb/lib/operations/execute_operation.js:16:37)
        at Collection.updateOne (/app/node_modules/mongodb/lib/collection.js:169:57)
        at markOrganismeAsCollected (/app/src/jobs/collectSources.js:21:37)
        at /app/src/jobs/collectSources.js:225:17
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async ParallelWrite._onWrite (/app/node_modules/oleoduc/lib/writeData.js:99:19) {
      [Symbol(errorLabels)]: Set(0) {}
    }
  ]
}
```

**Comment by gasilber** [comment]
Ne s'est plus produit récemment.
