### ISSUE TITLE
URGENT : OF Impossible à fiabiliser / adresse et académie manqante

### ISSUE THREAD

**Issue by FlavieSauvebois** [mission-apprentissage/referentiel#246]
Hello, 

Je dois fiabiliser un OF (ajouter son UAI) dans le Référentiel : 88977538300033
Malheureusement, je n'ai pas la main sur l'UAI. Cet OF n'a pas d'adresse, donc pas d'académie ou de Région déduite et cela empêche sa fiabilisation.
Il faudrait corriger cela. Regarder pourquoi l'adresse ne remonte pas alors qu'il y a bien une adresse dans la base Sirène. 
J'ai regardé dans le Référentiel. Nous avons 34 OF sans académie ou Région, donc avec le même problème. 
C'est assez urgent. Merci.

**Comment by gasilber** [comment]
Cet organisme provoque une erreur de schéma, il semble manquer le code postal (pourquoi?).

```json
[2024-12-17T04:49:32.840Z][WARN][collect] Erreur lors de la collecte pour l'organisme 88977538300033. { source: 'catalogue' }
{
  anomalies: [
    MongoServerError: Document failed validation
        at /app/node_modules/mongodb/lib/operations/update.js:85:33
        at /app/node_modules/mongodb/lib/cmap/connection_pool.js:273:25
        at handleOperationResult (/app/node_modules/mongodb/lib/sdam/server.js:327:20)
        at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:215:9)
        at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:63:60)
        at MessageStream.emit (node:events:517:28)
        at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
        at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
        at writeOrBuffer (node:internal/streams/writable:392:12)
        at _write (node:internal/streams/writable:333:10) {
      index: 0,
      code: 121,
      errInfo: {
        failingDocumentId: new ObjectId("66c809e9e5cd44b917b773f0"),
        details: {
          operatorName: '$jsonSchema',
          schemaRulesNotSatisfied: [
            {
              operatorName: 'properties',
              propertiesNotSatisfied: [
                {
                  propertyName: 'lieux_de_formation',
                  details: [
                    {
                      operatorName: 'items',
                      reason: 'At least one item did not match the sub-schema',
                      itemIndex: 0,
                      details: [
                        {
                          operatorName: 'properties',
                          propertiesNotSatisfied: [
                            {
                              propertyName: 'adresse',
                              details: [
                                {
                                  operatorName: 'properties',
                                  propertiesNotSatisfied: [
                                    {
                                      propertyName: 'code_postal',
                                      details: [
                                        {
                                          operatorName: 'bsonType',
                                          specifiedAs: { bsonType: 'string' },
                                          reason: 'type did not match',
                                          consideredValue: null,
                                          consideredType: 'null'
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      [Symbol(errorLabels)]: Set(0) {}
    }
  ]
}
```

Validation à la main:

```
root@gordolasque:/home/gasilber# bash /opt/referentiel/cli.sh modify 88977538300033 9711303P
```
