### ISSUE TITLE
Correction de l'import CFD

### ISSUE THREAD

**Issue by gasilber** [mission-apprentissage/referentiel#247]
```
[2024-12-19T12:00:22.250Z][ERROR][import] Impossible d'importer le code formation diplome  undefined
MongoServerError: Document failed validation
    at /app/node_modules/mongodb/lib/operations/update.js:85:33
    at /app/node_modules/mongodb/lib/cmap/connection_pool.js:273:25
    at handleOperationResult (/app/node_modules/mongodb/lib/sdam/server.js:327:20)
    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:215:9)
    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:63:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10) 
{
  err: {
    errInfo: {
      failingDocumentId: new ObjectId("67640ad64889add9e695dc0d"),
      details: {
        operatorName: '$jsonSchema',
        schemaRulesNotSatisfied: [
          {
            operatorName: 'properties',
            propertiesNotSatisfied: [
              {
                propertyName: 'FORMATION_DIPLOME',
                details: [
                  {
                    operatorName: 'bsonType',
                    specifiedAs: { bsonType: 'string' },
                    reason: 'type did not match',
                    consideredValue: null,
                    consideredType: 'null'
                  }
                ]
              }
            ]
          },
          {
            operatorName: 'required',
            specifiedAs: {
              required: [
                'FORMATION_DIPLOME',
                'NIVEAU_FORMATION_DIPLOME',
                'LIBELLE_COURT'
              ]
            },
            missingProperties: [ 'LIBELLE_COURT', 'NIVEAU_FORMATION_DIPLOME' ]
          }
        ]
      }
    }
  }
}
```

**Comment by gasilber** [comment]
Corrigé par https://github.com/mission-apprentissage/referentiel/commit/e37e20e506fd24f5a9d00804f65dbf5b7f26d040
